STRONGSORT:
  ECC: True              # activate camera motion compensation
  MC_LAMBDA: 0.995       # matching with both appearance (1 - MC_LAMBDA) and motion cost
  EMA_ALPHA: 0.9         # updates  appearance  state in  an exponential moving average manner
  MAX_DIST: 0.1          # The matching (similarity?) threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 0.7  # Gating threshold (?). Associations with cost larger than this value are disregarded.
  MAX_AGE: 500           # Maximum number of missed misses before a track is deleted
  N_INIT: 3              # Number of frames that a track remains in initialization phase
  NN_BUDGET: 100         # Maximum size of the appearance descriptors gallery
  UNATTENDED_BAG_MIN_HITS: 3 # Minimum number of hits (frames) for an object to be flagged as unattended
  
# From observation:
# - similarity metric too insensitive, causing different objects to be tagged to same index. 
    # - change max_dist from 0.2 to 0.1
